// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoFast.Segmentation.Data;

#nullable disable

namespace ProtoFast.Segmentation.Data.Migrations
{
    [DbContext(typeof(SegmentationDbContext))]
    partial class SegmentationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.FamilyInstinct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer")
                        .HasColumnName("confirmations");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("family");

                    b.Property<string>("Guidance")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("guidance");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pattern");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.HasKey("Id")
                        .HasName("pk_family_instincts");

                    b.HasIndex("Family", "Pattern")
                        .IsUnique()
                        .HasDatabaseName("ix_family_instincts_family_pattern");

                    b.ToTable("family_instincts", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.ModelCall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<bool>("Batched")
                        .HasColumnType("boolean")
                        .HasColumnName("batched");

                    b.Property<int>("CachedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_input_tokens");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("LimitPool")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("limit_pool");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_model_calls");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_model_calls_run_id");

                    b.HasIndex("Provider", "At")
                        .HasDatabaseName("ix_model_calls_provider_at");

                    b.ToTable("model_calls", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.Qualification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_key");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<bool>("Qualified")
                        .HasColumnType("boolean")
                        .HasColumnName("qualified");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_qualifications");

                    b.HasIndex("ModelKey", "Role", "PromptVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_qualifications_model_key_role_prompt_version");

                    b.ToTable("qualifications", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.ReviewTask", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.Property<string>("DocumentFamily")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_family");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_id");

                    b.Property<string>("EditsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edits_json");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings_json");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_subject");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("WorkflowRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("workflow_request_id");

                    b.HasKey("ReviewId")
                        .HasName("pk_review_tasks");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_review_tasks_run_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_review_tasks_status_created_at");

                    b.ToTable("review_tasks", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.Run", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("Augmentations")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("augmentations");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("condition");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentFamily")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_family");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_subject");

                    b.Property<string>("PinnedModels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pinned_models");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_review");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_state");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("TreeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tree_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upload_id");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("OwnerSubject", "CreatedAt")
                        .HasDatabaseName("ix_runs_owner_subject_created_at");

                    b.HasIndex("OwnerSubject", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_runs_owner_subject_idempotency_key");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.RunEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_run_events");

                    b.HasIndex("RunId", "Id")
                        .HasDatabaseName("ix_run_events_run_id_id");

                    b.ToTable("run_events", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.RunPhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("artifact_key");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<int>("RepairRounds")
                        .HasColumnType("integer")
                        .HasColumnName("repair_rounds");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_run_phases");

                    b.HasIndex("RunId", "Phase")
                        .IsUnique()
                        .HasDatabaseName("ix_run_phases_run_id_phase");

                    b.ToTable("run_phases", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.RunResult", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("AugmentationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("augmentations_json");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_subject");

                    b.Property<string>("ParagraphsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("paragraphs_json");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TreeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tree_hash");

                    b.Property<string>("TreeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tree_json");

                    b.HasKey("RunId")
                        .HasName("pk_run_results");

                    b.HasIndex("OwnerSubject", "DocumentId")
                        .HasDatabaseName("ix_run_results_owner_subject_document_id");

                    b.ToTable("run_results", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.Upload", b =>
                {
                    b.Property<string>("UploadId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upload_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_subject");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<bool>("WithLayout")
                        .HasColumnType("boolean")
                        .HasColumnName("with_layout");

                    b.HasKey("UploadId")
                        .HasName("pk_uploads");

                    b.HasIndex("OwnerSubject", "CreatedAt")
                        .HasDatabaseName("ix_uploads_owner_subject_created_at");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.RunEvent", b =>
                {
                    b.HasOne("ProtoFast.Segmentation.Data.Entities.Run", "Run")
                        .WithMany("Events")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_events_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.RunPhase", b =>
                {
                    b.HasOne("ProtoFast.Segmentation.Data.Entities.Run", "Run")
                        .WithMany("Phases")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_phases_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ProtoFast.Segmentation.Data.Entities.Run", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
