// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoFast.Data.ThePlot;

#nullable disable

namespace ProtoFast.Data.Migrations
{
    [DbContext(typeof(ThePlotDbContext))]
    [Migration("20260925021752_AddScreenplay")]
    partial class AddScreenplay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plot")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Act", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_acts");

                    b.HasIndex("DraftId", "Position")
                        .HasDatabaseName("ix_acts_draft_id_position");

                    b.ToTable("acts", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_acts_position_non_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.CastMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<int>("Hue")
                        .HasColumnType("integer")
                        .HasColumnName("hue");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cast_members");

                    b.HasIndex("StoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cast_members_story_id_name");

                    b.ToTable("cast_members", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_cast_members_hue", "hue BETWEEN 0 AND 359");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("UserId", "DateCreated")
                        .HasDatabaseName("ix_documents_user_id_date_created");

                    b.ToTable("documents", "plot");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.DocumentUpload", b =>
                {
                    b.Property<string>("UploadId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("upload_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("UploadId")
                        .HasName("pk_document_uploads");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_document_uploads_user_id");

                    b.ToTable("document_uploads", "plot");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_drafts");

                    b.HasIndex("StoryId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_drafts_story_id_number");

                    b.ToTable("drafts", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_drafts_number_positive", "number >= 1");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<int>("Hue")
                        .HasColumnType("integer")
                        .HasColumnName("hue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("setting");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("StoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_story_id_name");

                    b.ToTable("locations", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_locations_hue", "hue BETWEEN 0 AND 359");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Prop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_props");

                    b.HasIndex("StoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_props_story_id_name");

                    b.ToTable("props", "plot");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActId")
                        .HasColumnType("uuid")
                        .HasColumnName("act_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("ActId", "Position")
                        .HasDatabaseName("ix_scenes_act_id_position");

                    b.ToTable("scenes", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_scenes_position_non_negative", "position >= 0");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.SceneElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Parenthetical")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parenthetical");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<Guid?>("SpeakerId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("time_of_day");

                    b.Property<string>("TransitionKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transition_kind");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_scene_elements");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_scene_elements_location_id");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_scene_elements_speaker_id");

                    b.HasIndex("SceneId", "Position")
                        .HasDatabaseName("ix_scene_elements_scene_id_position");

                    b.ToTable("scene_elements", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_scene_elements_dialogue_columns", "type = 'Dialogue' OR (speaker_id IS NULL AND parenthetical IS NULL)");

                            t.HasCheckConstraint("ck_scene_elements_heading_columns", "(type = 'Heading') = (time_of_day IS NOT NULL) AND (location_id IS NULL OR type = 'Heading')");

                            t.HasCheckConstraint("ck_scene_elements_position_non_negative", "position >= 0");

                            t.HasCheckConstraint("ck_scene_elements_text_columns", "(type IN ('Heading', 'Transition')) = (text IS NULL)");

                            t.HasCheckConstraint("ck_scene_elements_transition_columns", "(type = 'Transition') = (transition_kind IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.SceneElementMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CastMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("cast_member_id");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<int>("Offset")
                        .HasColumnType("integer")
                        .HasColumnName("offset");

                    b.Property<Guid?>("PropId")
                        .HasColumnType("uuid")
                        .HasColumnName("prop_id");

                    b.Property<Guid>("SceneElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_element_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_scene_element_mentions");

                    b.HasIndex("CastMemberId")
                        .HasDatabaseName("ix_scene_element_mentions_cast_member_id");

                    b.HasIndex("PropId")
                        .HasDatabaseName("ix_scene_element_mentions_prop_id");

                    b.HasIndex("SceneElementId")
                        .HasDatabaseName("ix_scene_element_mentions_scene_element_id");

                    b.ToTable("scene_element_mentions", "plot", t =>
                        {
                            t.HasCheckConstraint("ck_scene_element_mentions_one_target", "(cast_member_id IS NULL) <> (prop_id IS NULL)");

                            t.HasCheckConstraint("ck_scene_element_mentions_span", "\"offset\" >= 0 AND length >= 2");
                        });
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_modified");

                    b.Property<string>("SourceDocumentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("source_document_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stories");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_stories_source_document_id");

                    b.HasIndex("UserId", "DateLastModified")
                        .HasDatabaseName("ix_stories_user_id_date_last_modified");

                    b.ToTable("stories", "plot");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Act", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Draft", "Draft")
                        .WithMany("Acts")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acts_drafts_draft_id");

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.CastMember", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Story", "Story")
                        .WithMany("Cast")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cast_members_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Document", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.DocumentUpload", null)
                        .WithOne()
                        .HasForeignKey("ProtoFast.Data.ThePlot.Entities.Document", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_document_uploads_id");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Draft", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Story", "Story")
                        .WithMany("Drafts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drafts_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Location", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Story", "Story")
                        .WithMany("Locations")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Prop", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Story", "Story")
                        .WithMany("Props")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_props_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Scene", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Act", "Act")
                        .WithMany("Scenes")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenes_acts_act_id");

                    b.Navigation("Act");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.SceneElement", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scene_elements_locations_location_id");

                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Scene", "Scene")
                        .WithMany("Elements")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_elements_scenes_scene_id");

                    b.HasOne("ProtoFast.Data.ThePlot.Entities.CastMember", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scene_elements_cast_members_speaker_id");

                    b.Navigation("Location");

                    b.Navigation("Scene");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.SceneElementMention", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.CastMember", "CastMember")
                        .WithMany()
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_scene_element_mentions_cast_members_cast_member_id");

                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Prop", "Prop")
                        .WithMany()
                        .HasForeignKey("PropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_scene_element_mentions_props_prop_id");

                    b.HasOne("ProtoFast.Data.ThePlot.Entities.SceneElement", "SceneElement")
                        .WithMany("Mentions")
                        .HasForeignKey("SceneElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scene_element_mentions_scene_elements_scene_element_id");

                    b.Navigation("CastMember");

                    b.Navigation("Prop");

                    b.Navigation("SceneElement");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Story", b =>
                {
                    b.HasOne("ProtoFast.Data.ThePlot.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stories_documents_source_document_id");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Act", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Draft", b =>
                {
                    b.Navigation("Acts");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Scene", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.SceneElement", b =>
                {
                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("ProtoFast.Data.ThePlot.Entities.Story", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Drafts");

                    b.Navigation("Locations");

                    b.Navigation("Props");
                });
#pragma warning restore 612, 618
        }
    }
}
