// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoFast.DocumentImport.Data.Postgres;

#nullable disable

namespace ProtoFast.DocumentImport.Data.Migrations
{
    [DbContext(typeof(WorkflowEngineDbContext))]
    [Migration("20260925040350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyExecutor", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("ExecutorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("executor_id");

                    b.Property<int>("ExecutorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("executor_version");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("Family", "ExecutorId", "ExecutorVersion")
                        .HasName("pk_document_family_executors");

                    b.ToTable("document_family_executors", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyPolicyEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<double>("ConfidenceAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_alpha");

                    b.Property<double>("ConfidenceBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_beta");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_id");

                    b.Property<int?>("WorkflowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version");

                    b.HasKey("Family")
                        .HasName("pk_document_family_policies");

                    b.ToTable("document_family_policies", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyVerifier", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("VerifierId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verifier_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Rubric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.HasKey("Family", "VerifierId")
                        .HasName("pk_document_family_verifiers");

                    b.ToTable("document_family_verifiers", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.MinedWorkflowDraftEntry", b =>
                {
                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_id");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("Mined")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mined");

                    b.Property<DateTimeOffset>("MinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mined_at");

                    b.HasKey("WorkflowId", "WorkflowVersion")
                        .HasName("pk_mined_workflow_drafts");

                    b.ToTable("mined_workflow_drafts", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RegistryEntry", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<bool>("Promoted")
                        .HasColumnType("boolean")
                        .HasColumnName("promoted");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Kind", "Id", "Version")
                        .HasName("pk_registry_entries");

                    b.ToTable("registry_entries", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunDecisionEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choice");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.HasKey("Sequence")
                        .HasName("pk_run_decisions");

                    b.HasIndex("RunId", "Sequence")
                        .HasDatabaseName("ix_run_decisions_run_id_sequence");

                    b.ToTable("run_decisions", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Facets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facets");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trace_id");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("Family", "Mode", "ClosedAt")
                        .HasDatabaseName("ix_runs_family_mode_closed_at");

                    b.ToTable("runs", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StagePolicyEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("StageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.Property<double>("ConfidenceAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_alpha");

                    b.Property<double>("ConfidenceBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_beta");

                    b.Property<string>("Ladder")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ladder");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("primary");

                    b.Property<string>("Shadow")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shadow");

                    b.Property<double>("ShadowAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("shadow_alpha");

                    b.Property<double>("ShadowBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("shadow_beta");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Family", "StageId")
                        .HasName("pk_stage_policies");

                    b.ToTable("stage_policies", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StageRecordEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("record");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.HasKey("Sequence")
                        .HasName("pk_stage_records");

                    b.HasIndex("RunId", "Sequence")
                        .HasDatabaseName("ix_stage_records_run_id_sequence");

                    b.ToTable("stage_records", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunDecisionEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_decisions_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StageRecordEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_records_runs_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
