// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoFast.DocumentImport.Data.Postgres;

#nullable disable

namespace ProtoFast.DocumentImport.Data.Migrations
{
    [DbContext(typeof(WorkflowEngineDbContext))]
    [Migration("20261008052303_RunBriefs")]
    partial class RunBriefs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Family")
                        .HasName("pk_document_families");

                    b.ToTable("document_families", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyExecutor", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("ExecutorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("executor_id");

                    b.Property<int>("ExecutorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("executor_version");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("Family", "ExecutorId", "ExecutorVersion")
                        .HasName("pk_document_family_executors");

                    b.ToTable("document_family_executors", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyGenerationEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset>("ResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_at");

                    b.HasKey("Family")
                        .HasName("pk_document_family_generations");

                    b.ToTable("document_family_generations", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyPolicyEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<double>("ConfidenceAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_alpha");

                    b.Property<double>("ConfidenceBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_beta");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_id");

                    b.Property<int?>("WorkflowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version");

                    b.HasKey("Family")
                        .HasName("pk_document_family_policies");

                    b.ToTable("document_family_policies", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilySkill", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("SkillId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("skill_id");

                    b.Property<int>("SkillVersion")
                        .HasColumnType("integer")
                        .HasColumnName("skill_version");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("Family", "SkillId", "SkillVersion")
                        .HasName("pk_document_family_skills");

                    b.ToTable("document_family_skills", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.DocumentFamilyVerifier", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("VerifierId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verifier_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Rubric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.HasKey("Family", "VerifierId")
                        .HasName("pk_document_family_verifiers");

                    b.ToTable("document_family_verifiers", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.MinedWorkflowDraftEntry", b =>
                {
                    b.Property<string>("WorkflowId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_id");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("Mined")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mined");

                    b.Property<DateTimeOffset>("MinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mined_at");

                    b.HasKey("WorkflowId", "WorkflowVersion")
                        .HasName("pk_mined_workflow_drafts");

                    b.ToTable("mined_workflow_drafts", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RegistryEntry", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<bool>("Promoted")
                        .HasColumnType("boolean")
                        .HasColumnName("promoted");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Kind", "Id", "Version")
                        .HasName("pk_registry_entries");

                    b.ToTable("registry_entries", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunBriefEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Brief")
                        .HasColumnType("jsonb")
                        .HasColumnName("brief");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RunId")
                        .HasName("pk_run_briefs");

                    b.ToTable("run_briefs", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunDecisionEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choice");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.HasKey("Sequence")
                        .HasName("pk_run_decisions");

                    b.HasIndex("RunId", "Sequence")
                        .HasDatabaseName("ix_run_decisions_run_id_sequence");

                    b.ToTable("run_decisions", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abandoned_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Facets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facets");

                    b.Property<string>("Failure")
                        .HasColumnType("text")
                        .HasColumnName("failure");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trace_id");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("OpenedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_runs_opened_at");

                    b.HasIndex("Family", "Mode", "ClosedAt")
                        .HasDatabaseName("ix_runs_family_mode_closed_at");

                    b.ToTable("runs", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunMessageEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("RunId", "Sequence")
                        .HasName("pk_run_messages");

                    b.ToTable("run_messages", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunProgressEntry", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cost");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phase");

                    b.Property<string>("ResultId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result_id");

                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<string>("StageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SourceId")
                        .HasName("pk_run_progress");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_run_progress_run_id");

                    b.ToTable("run_progress", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunStepEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("step");

                    b.HasKey("RunId", "Sequence")
                        .HasName("pk_run_steps");

                    b.ToTable("run_steps", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunSystemPromptEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<int>("FromSequence")
                        .HasColumnType("integer")
                        .HasColumnName("from_sequence");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("RunId", "FromSequence")
                        .HasName("pk_run_system_prompts");

                    b.ToTable("run_system_prompts", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StagePolicyEntry", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("StageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.Property<double>("ConfidenceAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_alpha");

                    b.Property<double>("ConfidenceBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_beta");

                    b.Property<string>("Ladder")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ladder");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("primary");

                    b.Property<string>("Shadow")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shadow");

                    b.Property<double>("ShadowAlpha")
                        .HasColumnType("double precision")
                        .HasColumnName("shadow_alpha");

                    b.Property<double>("ShadowBeta")
                        .HasColumnType("double precision")
                        .HasColumnName("shadow_beta");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Family", "StageId")
                        .HasName("pk_stage_policies");

                    b.ToTable("stage_policies", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StageRecordEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("record");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("run_id");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.HasKey("Sequence")
                        .HasName("pk_stage_records");

                    b.HasIndex("RunId", "Sequence")
                        .HasDatabaseName("ix_stage_records_run_id_sequence");

                    b.ToTable("stage_records", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunBriefEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_briefs_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunDecisionEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_decisions_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunMessageEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_messages_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunStepEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_steps_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.RunSystemPromptEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_system_prompts_runs_run_id");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Postgres.Entities.StageRecordEntry", b =>
                {
                    b.HasOne("ProtoFast.DocumentImport.Data.Postgres.Entities.RunEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_records_runs_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
