// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProtoFast.DocumentImport.Data;

#nullable disable

namespace ProtoFast.DocumentImport.Data.Migrations
{
    [DbContext(typeof(WorkflowEngineDbContext))]
    partial class WorkflowEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Entities.DocumentFamilyExecutor", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("ExecutorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("executor_id");

                    b.Property<int>("ExecutorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("executor_version");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("Family", "ExecutorId", "ExecutorVersion")
                        .HasName("pk_document_family_executors");

                    b.ToTable("document_family_executors", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Entities.DocumentFamilyVerifier", b =>
                {
                    b.Property<string>("Family")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family");

                    b.Property<string>("VerifierId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verifier_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Rubric")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stage_id");

                    b.HasKey("Family", "VerifierId")
                        .HasName("pk_document_family_verifiers");

                    b.ToTable("document_family_verifiers", "engine");
                });

            modelBuilder.Entity("ProtoFast.DocumentImport.Data.Entities.RegistryEntry", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<bool>("Promoted")
                        .HasColumnType("boolean")
                        .HasColumnName("promoted");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Kind", "Id", "Version")
                        .HasName("pk_registry_entries");

                    b.ToTable("registry_entries", "engine");
                });
#pragma warning restore 612, 618
        }
    }
}
